"""Connect service facade — re-exports the split connect_* submodules."""

from services.connect_common import (
    SLUG_PATTERN,
    SESSION_TTL_MINUTES,
    CONNECT_METRICS,
    VALID_CONSENT_ACTIONS,
    GRANT_ACCESS_PREFIX,
    CONNECT_CODE_TTL_MINUTES,
    VALID_SESSION_MODES,
    OTP_ISSUE_MAX_PER_HOUR,
    GRANT_ACCESS_TTL_MINUTES,
    CONNECT_LATENCY,
    OTP_ISSUE_WINDOW_START,
    _serialize_session,
    _normalize_slug,
    _validate_redirect_uris,
    _session_provider,
    _audit,
    _app_redirect_url,
    _issue_connect_code,
    _parse_connect_code,
    _get_owned_app,
    _load_pending_session,
    _require_google_connect_config,
    _find_connect_user_by_verified_email,
    _require_authenticated_app_user,
    _attach_session_connect_user,
    finalize_connect_redirect,
    _find_or_create_connect_user_by_email,
    _build_grant_access_token,
    _parse_grant_access_token,
    _seconds_until,
)

from services.connect_apps import ensure_workspace_app

from services.connect_sessions import (
    attach_provider_identity,
    _issue_otp_challenge,
    resend_connect_otp,
    verify_connect_otp,
    _upsert_connection,
    _complete_session,
    create_connect_session,
    list_workspace_connections,
)

from services.connect_grants import (
    _ensure_grant,
    get_grant_context,
    get_current_grant,
    list_workspace_grants,
    create_grant,
    revoke_grant,
    approve_grant,
    deny_grant,
)

from services.connect_oauth import (
    _grant_authorize_redirect,
    connect_oauth_error_redirect,
    begin_connect_authorize,
    handle_connect_callback,
    get_connect_consent_page,
    submit_connect_consent,
    exchange_connect_token,
    list_connect_providers,
)

from services.connect_audit import (
    list_audit_events,
    get_connect_metrics,
)

__all__ = [
    'SLUG_PATTERN',
    'SESSION_TTL_MINUTES',
    'CONNECT_METRICS',
    'VALID_CONSENT_ACTIONS',
    'GRANT_ACCESS_PREFIX',
    'CONNECT_CODE_TTL_MINUTES',
    'VALID_SESSION_MODES',
    'OTP_ISSUE_MAX_PER_HOUR',
    'GRANT_ACCESS_TTL_MINUTES',
    'CONNECT_LATENCY',
    'OTP_ISSUE_WINDOW_START',
    '_serialize_session',
    '_normalize_slug',
    '_validate_redirect_uris',
    '_session_provider',
    '_audit',
    '_app_redirect_url',
    '_issue_connect_code',
    '_parse_connect_code',
    '_get_owned_app',
    '_load_pending_session',
    '_require_google_connect_config',
    '_find_connect_user_by_verified_email',
    '_require_authenticated_app_user',
    '_attach_session_connect_user',
    'finalize_connect_redirect',
    '_find_or_create_connect_user_by_email',
    '_build_grant_access_token',
    '_parse_grant_access_token',
    '_seconds_until',
    'ensure_workspace_app',
    'attach_provider_identity',
    '_issue_otp_challenge',
    'resend_connect_otp',
    'verify_connect_otp',
    '_upsert_connection',
    '_complete_session',
    'create_connect_session',
    'list_workspace_connections',
    '_ensure_grant',
    'get_grant_context',
    'get_current_grant',
    'list_workspace_grants',
    'create_grant',
    'revoke_grant',
    'approve_grant',
    'deny_grant',
    '_grant_authorize_redirect',
    'connect_oauth_error_redirect',
    'begin_connect_authorize',
    'handle_connect_callback',
    'get_connect_consent_page',
    'submit_connect_consent',
    'exchange_connect_token',
    'list_connect_providers',
    'list_audit_events',
    'get_connect_metrics',
]
